server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        cluster-name: SH #集群名称，代指杭州
#        namespace: a494b321-e138-4060-81ff-c71caae32b30
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#    client:
#      service-url: #eureka的地址信息
#        defaultZone: http://127.0.0.1:10086/eureka
feign:
  client:
    config:
      default:
        loggerLevel: FULL
